# Generated by Django 5.0.4 on 2024-04-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('price', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
